# Generated by Django 4.0 on 2022-08-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='title', max_length=20)),
                ('number_of_pages', models.IntegerField()),
                ('published_date', models.DateField()),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
