# Generated by Django 4.1 on 2022-08-30 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.CharField(default='describe', max_length=200),
            preserve_default=False,
        ),
    ]
